// This file is generated by the developer and should be kept in sync with the Rust backend.
// CONVENTIONS.md: Rust側の引数・フィールドはスネークケース（project_id）、TypeScript側はキャメルケース（projectId）を厳守する。

export type WbsElementType = 'Project' | 'WorkPackage' | 'Activity';

export interface Portfolio {
  id: number;
  name: string;
}

export interface PlanVersion {
  id: number;
  portfolioId: number;
  name: string;
  isDraft: boolean;
}

export interface WbsElementDetail {
  id: number;
  planVersionId: number;
  wbsElementId: number;
  parentElementId: number | null;
  milestoneId: number | null;
  title: string;
  description: string | null;
  elementType: WbsElementType;
  estimatedPv: number | null;
  tags: string | null; // JSON string
  isDeleted: boolean;
}

export interface PvAllocation {
  id: number;
  planVersionId: number;
  wbsElementId: number;
  userId: number | null;
  startDate: string; // "YYYY-MM-DD"
  endDate: string; // "YYYY-MM-DD"
  plannedValue: number;
}

export interface ActualCost {
  id: number;
  wbsElementId: number;
  userId: number;
  workDate: string; // "YYYY-MM-DD"
  actualCost: number;
  isDeleted: boolean;
}

export interface ProgressUpdate {
  id: number;
  wbsElementId: number;
  reportedByUserId: number;
  reportDate: string; // "YYYY-MM-DD"
  progressPercent: number;
  notes: string | null;
  isDeleted: boolean;
}

export interface EvmKpis {
  bac: number;
  pv: number;
  ev: number;
  ac: number;
  cpi: number;
  spi: number;
}

export interface User {
  id: number;
  name: string;
  role: string;
}

export interface PlanMilestone {
  id: number;
  planVersionId: number;
  milestoneId: number;
  name: string;
  targetDate: string; // "YYYY-MM-DD"
  isDeleted: boolean;
}

export interface SCurveDataPoint {
  date: string; // "YYYY-MM"
  cumulativePv: number;
  cumulativeEv: number;
  cumulativeAc: number;
  bac: number;
  plannedEtc: number;
  actualEtc: number;
}

export type Granularity = 'daily' | 'weekly' | 'monthly';
export type ChartType = 'SCurve' | 'EvEtcArea';

export interface WidgetConfig {
  id:string;
  title: string;
  chartType: ChartType;
  granularity: Granularity;
  wbsIds: number[];
  userIds: number[];
  milestoneIds: number[];
  tags: string[];
}
