// This file is generated by the developer and should be kept in sync with the Rust backend.
// CONVENTIONS.md: Rust側の引数・フィールドはスネークケース（project_id）、TypeScript側はキャメルケース（projectId）を厳守する。

export type WbsElementType = 'Project' | 'WorkPackage' | 'Activity';

export interface Project {
  id: number;
  name: string;
}

export interface PlanVersion {
  id: number;
  projectId: number;
  name: string;
  isDraft: boolean;
}

export interface WbsElementDetail {
  id: number;
  planVersionId: number;
  wbsElementId: number;
  parentElementId: number | null;
  milestoneId: number | null;
  title: string;
  description: string | null;
  elementType: WbsElementType;
  estimatedPv: number | null;
  tags: string | null; // JSON string
  isDeleted: boolean;
}

export interface PvAllocation {
  id: number;
  planVersionId: number;
  wbsElementId: number;
  userId: number | null;
  startDate: string; // "YYYY-MM-DD"
  endDate: string; // "YYYY-MM-DD"
  plannedValue: number;
}
